# -*- coding: utf-8 -*-
def Sakes():
    sakes = [
        {
            "id": "P00000001",
            "name": "Tenjin Bayashi Sake",
            "name_ja": "月桂冠",
            "type": "Junmai Ginjo",
            "type_ja": "純米吟醸",
            "is_fruity": "False",
            "maker": "Uonuma Sake Brewery",
            "maker_ja": "魚沼酒造",
            "region": "Kyoto",
            "region_ja": "京都府",
            "url": "https://www.sake-tour.jp/uonuma/?hl=en",
            "description":"",
            "description_ja":"",
            "image":"tenjin_bayashi_junmai_ginjo_front_1024x.jpg"
        },
        {
            "id": "P00000001",
            "name": "Gekkeikan",
            "name_ja": "月桂冠",
            "type": "Junmai Daiginjo",
            "type_ja": "純米大吟醸",
            "is_fruity": "False",
            "maker": "Gekkeikan Sake Company",
            "maker_ja": "月桂冠酒造",
            "region": "Tyoto",
            "region_ja": "京都府",
            "url": "http://www.gekkeikan.co.jp/company/guide/index.html",
            "description":"",
            "description_ja":"",
            "image":"15830.jpg"
        },
        {
            "id": "P00000002",
            "name": "Ozeki",
            "name_ja": "大関",
            "type": "Junmai Daiginjo",
            "type_ja": "純米大吟醸",
            "is_fruity": "False",
            "maker": "Ozeki",
            "maker_ja": "大関株式会社",
            "region": "Hyogo",
            "region_ja": "兵庫",
            "url": "https://www.ozeki.co.jp/about/gaiyou/",
            "description":"",
            "description_ja":"",
            "image":"ci-ozeki-sake-620c2d76359e67f5.jpeg"
        },
        {
            "id": "P00000003",
            "name": "Hakkaisan",
            "name_ja": "八海山",
            "type": "Junmai Daiginjo",
            "type_ja": "純米大吟醸",
            "is_fruity": "False",
            "maker": "HAKKAISAN CO., LTD.",
            "maker_ja": "八海醸造株式会社",
            "region": "Niigata",
            "region_ja": "新潟",
            "url": "https://www.hakkaisan.com/about-hakkaisan/company-profile/",
            "description":"",
            "description_ja":"",
            "image":"sake-hakkaisan.jpg"
        },
        {
            "id": "P00000004",
            "name": "Shochikubai",
            "name_ja": "松竹梅",
            "type": "Junmai",
            "type_ja": "純米",
            "is_fruity": "False",
            "maker": "Takarashuzo",
            "maker_ja": "宝酒造株式会社",
            "region": "Tokyo",
            "region_ja": "東京都",
            "url": "https://www.takarashuzo.co.jp/company/",
            "description":"",
            "description_ja":"",
            "image":"sho-chiku-bai-classic-junmai-sake.gif"
        },
        {
            "id": "P00000005",
            "name": "Kometomizunosake",
            "name_ja": "米と水の酒",
            "type": "Junmai",
            "type_ja": "純米",
            "is_fruity": "True",
            "maker": "Gekkeikan Sake Company",
            "maker_ja": "月桂冠酒造",
            "region": "Kyoto",
            "region_ja": "京都府",
            "url": "http://www.gekkeikan.co.jp/company/guide/index.html",
            "description":"",
            "description_ja":"",
            "image":"download.jpeg",
        }
   ]
    return sakes
